#swift-mailer:
#    transport: smtp
#    host: smtp.gmail.com
#    port: 587
#    encryption: tls
#    username: 'sitedesortie35@gmail.com'
#    password: 'Pa$$w0rd35'
#    url: '%env(MAILER_URL)%'
#    spool: { type: 'memory' }